[package]
name = "avm1-parser"
version = "0.0.1"
authors = ["Charles Samborski <demurgos@demurgos.net>"]
description = "AVM1 parser"
documentation = "https://github.com/open-flash/avm1-parser"
homepage = "https://github.com/open-flash/avm1-parser"
repository = "https://github.com/open-flash/avm1-parser"
readme = "./README.md"
keywords = ["ast", "swf", "avm1"]
license = "MIT"
edition = "2018"

[lib]
name = "avm1_parser"
path = "src/lib.rs"

[[bin]]
name = "avm1-parser"
path = "src/main.rs"

[dependencies]
hex = "^0.3.2"
libflate = "^0.1.18"
nom = "4.1.1"
rust-lzma = "^0.3.0"
serde = "^1.0.43"
serde_derive = "^1.0.80"
serde_json = "^1.0.32"
avm1-tree = "^0.0.15"

#[replace]
#"avm1-tree:0.0.14" = { path = '../../avm1-tree/rs' }
